mysite/catalog/urls.py
from django.urls import path
from .views import IndexView, AnimeListView, AnimeDetailView, CommentDeleteView


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('anime', AnimeListView.as_view(), name='anime_list'),
    path('anime/<slug:anime_slug>', AnimeDetailView.as_view(), name='anime_detail'),
    path('comment-delete/<slug:comm_slug>', CommentDeleteView.as_view(), name='comm_delete'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('accounts/', include('users.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/users/urls.py
from django.urls import path
from .views import LoginUserView, RegistrationUserView, ProfileUserView, logout_user, UserAnimeList, UserAnimeListDelete

urlpatterns = [
    path('login/', LoginUserView.as_view(), name='login'),
    path('registration/', RegistrationUserView.as_view(), name='registration'),
    path('profile/', ProfileUserView.as_view(), name='profile'),
    path('profile/logout', logout_user, name='logout'),
    path('profile/my_anime_list', UserAnimeList.as_view(), name='my_anime_list'),
    path('profile/my_anime_list/delete-from-list/<int:pk>', UserAnimeListDelete.as_view(), name='my_anime_list_delete'),
]

mysite/catalog/models.py
from django.db import models
from django.urls import reverse
from transliterate import slugify
from django.conf import settings


class Genre(models.Model):
    name = models.CharField(verbose_name='Наименование жанра аниме', max_length=200)
    slug = models.SlugField(verbose_name='Слаг', max_length=200, db_index=True, unique=True, null=True, blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name, 'ru')
        super().save()

    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'


class Anime(models.Model):
    class Age(models.TextChoices):
        AGE_G = 'g', 'G'
        AGE_PG = 'pg', 'PG'
        AGE_PG13 = 'pg13', 'PG-13'
        AGE_R = 'r', 'R'
        AGE_NC17 = 'nc17', 'NC-17'

    class Status(models.TextChoices):
        ONG = 'on', 'Онгоинг'
        OUT = 'out', 'Вышел'
        AN = 'an', 'Анонс'

    class Type(models.TextChoices):
        SERIAL = 'sr', 'Сериал'
        FILM = 'fl', 'Фильм'

    title = models.CharField(verbose_name='Наименование аниме', max_length=200)
    title_eng = models.CharField(verbose_name='Наименование аниме по англ.', max_length=200)
    slug = models.SlugField(verbose_name='Слаг', max_length=200, db_index=True, unique=True, null=True, blank=True)
    type = models.CharField(verbose_name='Тип аниме', max_length=2, choices=Type.choices)
    episodes = models.PositiveSmallIntegerField(verbose_name='Количество серий в сезоне', null=True, blank=True)
    status = models.CharField(verbose_name='Статус аниме', max_length=3, choices=Status.choices)
    genres = models.ManyToManyField(to=Genre, verbose_name='Жанры аниме', db_index=True)
    studia = models.CharField(verbose_name='Студия', max_length=200, null=True, blank=True)
    age_restrictions = models.CharField(verbose_name='Возрастное ограничение', max_length=4, choices=Age.choices)
    year = models.PositiveIntegerField(verbose_name='Год выпуска аниме')
    create_date = models.DateTimeField(verbose_name='Дата добавления аниме', auto_now_add=True)
    description_full = models.TextField(verbose_name='Полное описание аниме')
    description_partial = models.CharField(verbose_name='Краткое описание аниме', max_length=300)
    poster_image = models.ImageField(verbose_name='Изображение постера аниме', upload_to='posters/')
    duration = models.CharField(verbose_name='Длительность', max_length=200, null=True, blank=True, help_text='Поле для аниме-фильмов')
    author = models.CharField(verbose_name='Автор', max_length=200, null=True, blank=True, help_text='Поле для аниме-фильмов')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title, 'ru')
        super().save()

    def get_absolute_url(self):
        return reverse("anime_detail", kwargs={"anime_slug": self.slug})

    class Meta:
        verbose_name = 'Аниме'
        verbose_name_plural = 'Аниме'


class AnimeShots(models.Model):
    image = models.ImageField(verbose_name='Изображение постера аниме', upload_to='anime-shorts/')
    anime = models.ForeignKey(verbose_name='Аниме', to=Anime, on_delete=models.CASCADE)

    def __str__(self):
        return f'Кадр из аниме - {self.anime.title}'

    class Meta:
        verbose_name = 'Кадр из аниме'
        verbose_name_plural = 'Кадры из аниме'


class Comment(models.Model):
    anime = models.ForeignKey(verbose_name='Аниме', to=Anime, on_delete=models.CASCADE)
    author = models.ForeignKey(verbose_name='Автор', to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField(verbose_name='Текст комментария')
    date_created = models.DateTimeField(verbose_name='Дата создания', auto_now_add=True)
    slug = models.SlugField(verbose_name='Слаг', max_length=200, db_index=True, unique=True, null=True, blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.content + str(self.author.pk), 'ru')
        super().save()

    def __str__(self):
        return f'{self.author.username} | {self.anime.title}'

    def get_absolute_url(self):
        return reverse("comm_delete", kwargs={"comm_slug": self.slug})

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

mysite/catalog/forms.py
from django import forms
from .models import Comment
from users.models import UserAnimeWatchPlanned


class AddCommentForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'form-control',
        'rows': '4',
        'placeholder': 'Текст комментария...',
    }))

    class Meta:
        model = Comment
        fields = [
            'content',
        ]


class AddAnimeToList(forms.ModelForm):
    status = forms.ChoiceField(choices=UserAnimeWatchPlanned.Status.choices, widget=forms.Select)

    class Meta:
        model = UserAnimeWatchPlanned
        fields = [
            'status',
        ]

mysite/catalog/views.py
from django.views.generic import ListView, DetailView, DeleteView
from .models import Anime, AnimeShots, Comment
from django.views.generic.edit import FormMixin
from .forms import AddCommentForm, AddAnimeToList
from django.urls import reverse_lazy
from users.models import UserAnimeWatchPlanned


class IndexView(ListView):
    model = Anime
    template_name = 'catalog/index.html'
    context_object_name = 'anime_list'

    def get_queryset(self):
        queryset = {
            'top_anime': Anime.objects.all()[:5],
            'last_anime': Anime.objects.order_by('-create_date')[:5],
        }

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'AnimeOne'

        return context


class AnimeListView(ListView):
    model = Anime
    template_name = 'catalog/anime.html'
    context_object_name = 'anime_list'
    paginate_by = 3

    def get_queryset(self):
        queryset = Anime.objects.all().prefetch_related('genres')

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Каталог аниме'

        return context


class AnimeDetailView(FormMixin, DetailView):
    model = Anime
    template_name = 'catalog/anime-detail.html'
    context_object_name = 'anime'
    slug_url_kwarg = 'anime_slug'
    form_class = AddCommentForm
    second_form_class = AddAnimeToList

    def get_success_url(self):
        return reverse_lazy('index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.object.title
        context['anime_shorts'] = AnimeShots.objects.filter(anime_id=self.object.pk)
        context['comments'] = Comment.objects.filter(anime_id=self.object.pk).order_by('-date_created').select_related('author', 'anime')
        context['form'] = self.get_form()
        context['form_2'] = self.second_form_class()

        return context

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        form_2 = self.second_form_class(request.POST)
        current_anime = self.get_object()

        if 'form1_sub' in request.POST:
            if form.is_valid():
                comm = form.save(commit=False)
                comm.anime_id = current_anime.pk
                comm.author_id = request.user.pk
                comm.save()
                return self.form_valid(form)
            else:
                return self.form_invalid(form)
        elif 'form2_sub' in request.POST:
            if form_2.is_valid():
                obj = UserAnimeWatchPlanned.objects.filter(anime_id=current_anime.pk, user_id=request.user.pk).first()
                if obj:
                    print(form_2.cleaned_data)
                    obj.status = form_2.cleaned_data['status']
                    obj.save()
                    return self.form_valid(form_2)
                else:
                    obj = form_2.save(commit=False)
                    obj.anime_id = current_anime.pk
                    obj.user_id = request.user.pk
                    obj.save()
                    return self.form_valid(form_2)
            else:
                return self.form_invalid(form_2)


class CommentDeleteView(DeleteView):
    model = Comment
    slug_url_kwarg = 'comm_slug'
    template_name = 'catalog/delete-confirm.html'
    context_object_name = 'comment'

    def get_success_url(self):
        return reverse_lazy('index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Удаление комментария'

        return context

mysite/catalog/templates/catalog/anime-detail.html
{% extends "catalog/base.html" %}

{% block bootstrap %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
{% endblock bootstrap %}

{% block menu %}
    <ol class="header-menu">
{% endblock menu %}

{% block content %}
<div class="wrapper">
    <div class="main-inner-double">
        <div class="main-block-anime-detail">
            <div class="main-block-anime-detail-left">
                <img class="main-block-anime-detail-left-img" src="{{ anime.poster_image.url }}" alt="Logo">
                <form method="POST">
                    {% csrf_token %}
                    <div class="custom-dropdown big">
                        {{form_2.status}}
                    </div>
                    <button type="submit" class="btn btn-success" name="form2_sub">Подтвердить</button>
                </form>
                <div class="rating-area">
                    <input type="radio" id="star-5" name="rating" value="5">
                    <label for="star-5" title="Оценка «5»"></label>
                    <input type="radio" id="star-4" name="rating" value="4">
                    <label for="star-4" title="Оценка «4»"></label>
                    <input type="radio" id="star-3" name="rating" value="3">
                    <label for="star-3" title="Оценка «3»"></label>
                    <input type="radio" id="star-2" name="rating" value="2">
                    <label for="star-2" title="Оценка «2»"></label>
                    <input type="radio" id="star-1" name="rating" value="1">
                    <label for="star-1" title="Оценка «1»"></label>
                </div>
            </div>
            <div class="main-block-anime-detail-right">
                <h1 class="main-block-anime-detail-right-h">{{ anime.title }}</h1>
                <p class="main-block-anime-detail-right-desc">{{ anime.title_eng }}</p>
                <div class="line"></div>
                <div class="main-block-anime-detail-right-main">
                    <div class="main-block-anime-detail-right-main-left">
                        <p class="p-item p-item-color">Тип</p>
                        {% if anime.get_type_display == 'Сериал' %}
                        <p class="p-item p-item-color">Эпизоды</p>
                        {% else %}
                        <p class="p-item p-item-color">Длительность</p>
                        {% endif %}
                        <p class="p-item p-item-color">Статус</p>
                        <p class="p-item p-item-color">Год</p>
                        <p class="p-item p-item-color">Жанры</p>
                        {% if anime.get_type_display == 'Фильм' %}
                            <p class="p-item p-item-color">Студия</p>
                            <p class="p-item p-item-color">Автор</p>
                        {% else %}
                            <p class="p-item p-item-color">Студия</p>
                        {% endif %}
                        <p class="p-item p-item-color">Возрастные ограничения</p>
                    </div>
                    <div class="main-block-anime-detail-right-main-right">
                        <p class="p-item">{{ anime.get_type_display }}</p>
                        {% if anime.get_type_display == 'Сериал' %}
                            <p class="p-item">{{ anime.episodes }}</p>
                        {% else %}
                            <p class="p-item">{{ anime.duration }}</p>
                        {% endif %}
                        <p class="p-item">{{ anime.get_status_display }}</p>
                        <p class="p-item">{{ anime.year }}</p>
                        <p class="p-item">{{ anime.genres.all|join:", " }}</p>
                        {% if anime.get_type_display == 'Фильм' %}
                            <p class="p-item">{{ anime.studia }}</p>
                            <p class="p-item">{{ anime.author }}</p>
                        {% else %}
                            <p class="p-item">{{ anime.studia }}</p>
                        {% endif %}
                        <p class="p-item">{{ anime.get_age_restrictions_display }}</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="main-block-anime-detail-bottom">
            <p class="main-block-anime-detail-bottom-desc">{{ anime.description_full }}</p>
            <h2 class="main-block-anime-detail-bottom-h2">Кадры</h2>
            <div class="main-block-anime-detail-bottom-block-img">
                {% for short in anime_shorts %}
                <img class="main-block-anime-detail-bottom-block-img-screen" src="{{ short.image.url }}"
                    alt="Logo">
                {% endfor %}
            </div>
        </div>
        <div class="main-block-anime-detail-bottom">
            <h2 class="main-block-anime-detail-bottom-h2">Комментарии</h2>
            {% if user.is_authenticated %}
            <form method="POST">
                {% csrf_token %}
                <div class="form-outline">
                    {{ form.content }}
                </div>
                <br>
                <button type="submit" class="btn btn-success" name="form1_sub">Отправить</button>
            </form>
            {% endif %}
            <br>
            {% for comm in comments %}
            <div class="main-block-anime-detail-bottom-comment">
                <div class="img_obertka">
                    <img class="main-block-anime-detail-bottom-comment-img" src="{{ comm.author.image.url }}"
                        alt="Logo">
                </div>
                <div class="main-block-anime-detail-bottom-comment-content">
                    <div class="main-block-anime-detail-bottom-comment-content-namedata">
                        <a class="main-block-anime-detail-bottom-comment-content-name" href="#">{{ comm.author.username }}</a>
                        <p class="main-block-anime-detail-bottom-comment-content-data">{{ comm.date_created }}</p>
                        {% if comm.author.pk == request.user.pk %}
                        <a class="main-block-anime-detail-bottom-comment-content-delete" href="{{ comm.get_absolute_url }}">Удалить</a>
                        {% endif %}
                    </div>
                    <p class="main-block-anime-detail-bottom-comment-content-text">{{ comm.content }}</p>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock content %}

{% block jsc %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script>
{% endblock jsc %}

        

mysite/catalog/templates/catalog/anime.html
{% extends "catalog/base.html" %}

{% block menu %}
    <ol class="header-menu-index">
{% endblock menu %}

{% block content %}
<div class="wrapper">
    <div class="main-block-new-anime">
        <div class="main-block-inner">
            <h1 class="block-title-h">Список аниме</h1>
            <div class="main-block-inner-two">
                <div class="main-block-list-anime">
                    {% for anime in anime_list%}
                    <div class="main-block-list-anime-card">
                        <img class="main-block-list-anime-card-img" src="{{anime.poster_image.url}}"
                            alt="Logo">
                        <div class="block-margin">
                            <a class="main-block-list-anime-card-a" href="{{ anime.get_absolute_url }}">{{ anime.title }}</a>
                            <p class="main-block-list-anime-card-eng">{{ anime.title_eng }}</p>
                            <div class="main-block-list-anime-card-type-row">
                                <a class="main-block-list-anime-card-type-row-a" href="#">{{ anime.get_type_display }}</a>
                                <a class="main-block-list-anime-card-type-row-a" href="#">{{ anime.year }}</a>
                                <a class="main-block-list-anime-card-type-row-a" href="#">{{ anime.genres.all|join:", " }}</a>
                            </div>
                            <p class="main-block-list-anime-card-p">{{ anime.description_partial }}</p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <div class="main-block-filter">

                </div>
            </div>
            {% if is_paginated %}
                <div class="pagination">
                    {% if page_obj.has_previous %}
                        <a href="?page={{page_obj.previous_page_number}}">«</a>
                    {% else %}
                        <a class="non-activate">«</a>
                    {% endif %}
                    {% for page in paginator.page_range %}
                        <a href="?page={{page}}">{{page}}</a>
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <a href="?page={{page_obj.next_page_number}}">»</a>
                    {% else %}
                        <a class="non-activate">»</a>
                    {% endif %}
                </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

mysite/catalog/templates/catalog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Gloria+Hallelujah&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu&display=swap" rel="stylesheet">
    {% block bootstrap %}{% endblock bootstrap %}
</head>

<body>
    <header class="header">
        <div class="wrapper">
            <a class="header-logo" href="{% url 'index' %}">AnimeOne</a>
            {% block menu %}{% endblock menu %}
                <li><a href="{% url 'anime_list' %}" class="header-menu-item">Аниме</a></li>
                <li><a href="" class="header-menu-item">Манга</a></li>
                <li><a href="" class="header-menu-item">Ранобэ</a></li>
                <li><a href="" class="header-menu-item">Новости</a></li>
            </ol>
            <div class="header-icons">
                <a href="#"><img class="header-icons-icon" src="{% static 'img/icons/search.svg' %}" alt="Search"></a>
                {% if user.is_authenticated %}
                    <a href="{% url 'profile' %}"><img class="header-icons-icon" src="{% static 'img/icons/profile.png' %}" alt="Profile"></a>
                {% else %}
                    <a href="{% url 'login' %}"><img class="header-icons-icon" src="{% static 'img/icons/profile.png' %}" alt="Profile"></a>
                {% endif %}
            </div>
        </div>
    </header>
    <div class="main">
        {% block content %}{% endblock content %}
    </div>
    <footer class="footer">
        <div class="wrapper">
            <a href="{% url 'index' %}" class="footer-title">AnimeOne</a>
        </div>
    </footer>
    {% block jsc %}{% endblock jsc %}
</body>

</html>

mysite/catalog/templates/catalog/delete-confirm.html
{% extends "catalog/base.html" %}
{% load static %}

{% block bootstrap %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
{% endblock bootstrap %}

{% block menu %}
<ol class="header-menu">
{% endblock menu %}

{% block content %}
        <div class="wrapper">
            <div class="main-block-new-anime">
                <div class="main-block-inner">
                    <h1 class="block-title-h">Вы действительно хотите удалить комментарий?</h1>
                    <div class="main-block-login">
                        <form method="POST">
                            {% csrf_token %}
                            <div class="main-block-delete-comm-buttons-row">
                                <button type="submit" class="btn btn-success">Подтверждаю</button>
                                <a class="main-block-delete-comm-buttons-row-back" href="{{ comment.anime.get_absolute_url }}">Отмена</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
{% endblock content %}

{% block jsc %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
                crossorigin="anonymous"></script>
{% endblock jsc %}   

mysite/catalog/templates/catalog/index.html
{% extends "catalog/base.html" %}
{% load static %}

{% block menu %}
    <ol class="header-menu-index">  
{% endblock %}

{% block content %}
<div class="main-block-title">
    <div class="wrapper">
        <div class="main-block-inner">
            <h1 class="block-title-h">AnimeOne - бесплатный каталог ваших просмотренных аниме!</h1>
            <p class="block-title-p">Аниме - это искусство японской анимации предназначенной в основном для
                подростков и лиц более
                старшего возраста. Именно поэтому японское аниме завоевала огромную популярность во всём мире.
            </p>
            <br>
            <p class="block-title-p">Теперь вы немного знаете о том, что такое аниме. А теперь я предлагаю вам
                окунуться с головой и
                отправиться в волшебный мир
                аниме. Я обещаю вам, что этот мир вам обязательно понравится и вы сможете найти жанр, который
                будет вам особенно интересен.</p>
        </div>
    </div>
</div>
<div class="main-block-new-anime">
    <div class="wrapper">
        <div class="main-block-inner">
            <h1 class="block-title-h">Новинки аниме</h1>
            <div class="main-block-new-anime-row">
                {% for anime_last in anime_list.last_anime %}
                <div class="main-block-new-anime-row-card">
                    <img class="main-block-new-anime-row-card-img" src="{{anime_last.poster_image.url}}"
                        alt="Logo">
                    <a class="main-block-new-anime-row-card-a" href="{{anime_last.get_absolute_url}}">{{anime_last.title}}</a>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
<div class="main-block-popular-anime">
    <div class="wrapper">
        <div class="main-block-inner">
            <h1 class="block-title-h">Популярные аниме</h1>
            <div class="main-block-new-anime-row">
                {% for anime_top in anime_list.top_anime %}
                <div class="main-block-new-anime-row-card">
                    <img class="main-block-new-anime-row-card-img" src="{{anime_top.poster_image.url}}"
                        alt="Logo">
                    <a class="main-block-new-anime-row-card-a" href="{{anime_top.get_absolute_url}}">{{anime_top.title}}</a>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}